apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: payments
    role: master
    tier: frontend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: idk
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: ssl
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: payments
  type: LoadBalancer
