var fx = require("money")
var currency = require('currency-code-map')
var request = require('request-promise')

//scraper stuff
var utils = require('./scrape_utils')

let fxRates //daily rates storage
const currencySpread = 0.03 //what's our currency spread


/**
 * Converts money value between currencies and adds spread percentage (i.e. KRW to USD)
 * @param {string} Base currency to convert FROM (i.e. KRW)
 * @param {string} Currency to convert TO (i.e. USD)
 * @param {number} The currency value to convert
 * @param {number} The spread percent to include on top
 * @returns {number} The new price converted to the requested currency
 */
module.exports.foreignExchange = async function (base,target,value,rates){
	if(rates && target in rates){
  		fx.rates = rates
	    value = fx.convert(value, {from: base, to: target})
	    //add an average currency spread on top of the conversion (3% on top of the currency value)
	    //to account for fluctuations between adding to the cart and the checkout
	    var sp = 1.00 + currencySpread
	    value = value * sp

	    return value.toFixed(2) //idk if we are rounding up here?
  	}
  	else {
  		console.log('conversion not found or something')
  	}
}

/**
 * Gets latest fx market rates
 * @returns {object} A list of currencies with corresponding rates
 */
module.exports.getRates = async function (){

	//are the rates older than an hour? if so, get new ones
	if (fxRates && fxRates.rates && fxRates.fetchDate && !utils.is_older_than_1hour(fxRates.fetchDate)){
		return fxRates.rates
	}

	//get conversion rates (updated daily). fixer.io is accurate-ish but not super accurate based on time of day, static on weekends, as it coincides when markets are open.
	//but a pretty good free service, backed by trusted, public data generated by an EU org.
	await request('http://api.fixer.io/latest', function (error, response, data) {
	  if (!error && response.statusCode == 200) {
	  	fxRates = JSON.parse(data)
	  	fxRates.fetchDate = new Date().toString()
	  }
	  else {
	  	console.log('ERROR '+response.statusCode+' IN CURRENCY EXCHANGE REQUEST! ', error)
	  }
	  return
	})

	return fxRates.rates
}

module.exports.storeFx = async function(rates,price,s){
	s.original_price.fx_rate = rates
    s.original_price.fx_rate_src = 'fixer.io'
    s.original_price.fx_on =  new Date()
    s.original_price.fx_spread = currencySpread
	s.price = price
	return s
}