image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

test_node:
  image: node:6
  stage: test
  script:
    - npm install
    - npm install --only=dev
    - npm install -g mocha
    - NODE_ENV=test PRINT_DATA=true mocha --require should --reporter spec tests/parser/parser.test.js

test_python:
  image: python:3
  stage: test
  script:
    - python3 --version
    - ls
    - pwd
    - pip install -r src/image_processing/requirements.txt
    - pytest tests/picstitch/

docker-build-push:
  image: docker:latest
  stage: build
  script:
    - docker login -u gcloud-docker@kip-styles.iam.gserviceaccount.com -u _json_key -p "$(cat src/k8s/other/gcloud.json)" https://gcr.io
    - docker build -t gcr.io/kip-styles/picstitch:$CI_BUILDREF -f Dockerfiles/picstitch.Dockerfile .
    - docker push gcr.io/kip-styles/picstitch:$CI_BUILDREF

k8s:
  image: docker:latest
  stage: deploy
  script:
    - sed -i "s/IMAGE_TAG/$CI_BUILDREF/" src/k8s/canary/canary.picstitch.yaml
    - echo "okay we did stuff"