image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build

cache:
  paths:
    - node_modules/

test_node:
  image: node:6
  stage: test
  script:
    - npm install
    - npm install --only=dev
    - npm install -g mocha
    - NODE_ENV=test PRINT_DATA=true mocha --require should --reporter spec tests/parser/parser.test.js

test_python:
  image: python:3.5
  stage: test
  script:
    - python3 --version
    - ls
    - pwd
    - pip install -r src/image_processing/requirements.txt
    - pytest tests/picstitch/

docker-build-push:
  stage: build
  script:
    - docker login -u gcloud-docker@kip-styles.iam.gserviceaccount.com -u _json_key -p "$(cat src/k8s/other/gcloud.json)" https://gcr.io
    - docker build -t gcr.io/kip-styles/picstitch:gitlab2 -f Dockerfiles/picstitch.Dockerfile .
    - docker push gcr.io/kip-styles/picstitch:gitlab2