apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: botbuilder
  name: botbuilder
spec:
  replicas: 1
  selector:
    matchLabels:
      run: botbuilder
  template:
    metadata:
      labels:
        run: botbuilder
    spec:
      containers:
      - image: gcr.io/kip-styles/botbuilder:aa5729c
        imagePullPolicy: IfNotPresent
        name: botbuilder
        ports:
        - containerPort: 4343
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
