apiVersion: v1
kind: Service
metadata:
  labels:
    run: botbuilder
  name: botbuilder
spec:
  ports:
  - port: 4343
    protocol: TCP
    targetPort: 4343
  selector:
    run: botbuilder
  type: LoadBalancer
