  kind: Service
  apiVersion: v1
  metadata:
    namespace: jenkins
  spec:
    type: NodePort
    selector:
      app: master
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
        name: ui
      - protocol: TCP
        port: 50000
        targetPort: 50000
        name: slaves
