apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-06-30T15:53:21Z
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "7"
  selfLink: /api/v1/namespaces/default/services/kubernetes
  uid: c55f18b9-3eda-11e6-bfee-42010af00138
spec:
  clusterIP: 10.3.240.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
