apiVersion: v1
kind: Service
metadata:
  name: nginx-pay
  labels:
    run: nginx-pay
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: nginx-pay
