apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nlp
  name: nlp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nlp
  template:
    metadata:
      labels:
        run: nlp
    spec:
      containers:
      - image: gcr.io/kip-styles/nlp:0.7.4.11
        imagePullPolicy: IfNotPresent
        name: nlp
        ports:
        - containerPort: 8083
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
