apiVersion: v1
kind: Service
metadata:
  labels:
    run: picstitch
  name: picstitch
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: picstitch
  type: ClusterIP
