apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: skype
  name: skype
spec:
  replicas: 1
  selector:
    matchLabels:
      run: skype
  template:
    metadata:
      labels:
        run: skype
    spec:
      containers:
      - image: gcr.io/kip-styles/skype:df4130e
        imagePullPolicy: Always
        name: skype
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
