apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: webhook
  name: webhook
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      run: webhook
  template:
    metadata:
      labels:
        run: webhook
    spec:
      containers:
      - image: gcr.io/kip-styles/webhook:latest
        imagePullPolicy: Always
        name: webhook
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: testing
  labels:
    run: webhook
spec:
  type: LoadBalancer
  ports:
  - nodePort: 30050
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: webhook
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: webhook-ingress
#   namespace: testing
# spec:
#   backend:
#     serviceName: webhook
#     servicePort: 5000
#   rules:
#   - host: dev-webhook.kipthis.com
#     http:
#       paths:
#       - backend:
#           serviceName: webhook
#           servicePort: 5000