apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: webhook
  name: webhook
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      run: webhook
  template:
    metadata:
      labels:
        run: webhook
    spec:
      containers:
      - image: gcr.io/kip-styles/webhook:latest
        imagePullPolicy: Always
        name: webhook
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: gitlab
  labels:
    run: webhook
spec:
  type: LoadBalancer
  ports:
  - nodePort: 30050
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: webhook