module.exports.cuisines = [
{name:"Afghan"},
{name:"African"},
{name:"Albanian"},
{name:"Alcohol"},
{name:"American"},
{name:"Argentinian"},
{name:"Asian"},
{name:"Australian"},
{name:"Austrian"},
{name:"Bagels"},
{name:"Bakery"},
{name:"BBQ"},
{name:"Belgian"},
{name:"Brazilian"},
{name:"Breakfast"},
{name:"British"},
{name:"Burmese"},
{name:"Cajun"},
{name:"Californian"},
{name:"Calzones"},
{name:"Cambodian"},
{name:"Cantonese"},
{name:"Caribbean"},
{name:"Cheesesteaks"},
{name:"Chicken"},
{name:"Chili"},
{name:"Chinese"},
{name:"Classic"},
{name:"Coffee and Tea"},
{name:"Colombian"},
{name:"Costa Rican"},
{name:"Crepes"},
{name:"Cuban"},
{name:"Deli"},
{name:"Dessert"},
{name:"Dim Sum"},
{name:"Diner"},
{name:"Dinner"},
{name:"Dominican"},
{name:"Eclectic"},
{name:"Ecuadorian"},
{name:"Egyptian"},
{name:"El Salvadoran"},
{name:"Empanadas"},
{name:"English"},
{name:"Ethiopian"},
{name:"Fast Food"},
{name:"Filipino"},
{name:"Fine Dining"},
{name:"French"},
{name:"Fresh Fruits"},
{name:"Frozen Yogurt"},
{name:"German"},
{name:"Gluten-Free"},
{name:"Greek"},
{name:"Grill"},
{name:"Grocery Items"},
{name:"Guatemalan"},
{name:"Gyro"},
{name:"Haitian"},
{name:"Halal"},
{name:"Hamburgers"},
{name:"Hawaiian"},
{name:"Healthy"},
{name:"Hoagies"},
{name:"Hot Dogs"},
{name:"Ice Cream"},
{name:"Indian"},
{name:"Indonesian"},
{name:"Irish"},
{name:"Italian"},
{name:"Jamaican"},
{name:"Japanese"},
{name:"Kids Menu"},
{name:"Korean"},
{name:"Kosher"},
{name:"Kosher-Style"},
{name:"Late Night"},
{name:"Latin American"},
{name:"Lebanese"},
{name:"Low Carb"},
{name:"Low Fat"},
{name:"Lunch"},
{name:"Lunch Specials"},
{name:"Malaysian"},
{name:"Mandarin"},
{name:"Mediterranean"},
{name:"Mexican"},
{name:"Middle Eastern"},
{name:"Mongolian"},
{name:"Moroccan"},
{name:"Nepalese"},
{name:"New American"},
{name:"Noodles"},
{name:"Organic"},
{name:"Pakistani"},
{name:"Pasta"},
{name:"Persian"},
{name:"Peruvian"},
{name:"Pitas"},
{name:"Pizza"},
{name:"Polish"},
{name:"Portuguese"},
{name:"Potato"},
{name:"Pub Food"},
{name:"Puerto Rican"},
{name:"Ribs"},
{name:"Russian"},
{name:"Salads"},
{name:"Sandwiches"},
{name:"Scandinavian"},
{name:"Seafood"},
{name:"Senegalese"},
{name:"Shakes"},
{name:"Smoothies and Juices"},
{name:"Soul Food"},
{name:"Soup"},
{name:"South African"},
{name:"South American"},
{name:"Southern"},
{name:"Southwestern"},
{name:"Spanish"},
{name:"Steak"},
{name:"Subs"},
{name:"Sushi"},
{name:"Szechwan"},
{name:"Taiwanese"},
{name:"Tapas"},
{name:"Tex-Mex"},
{name:"Thai"},
{name:"Tibetan"},
{name:"Turkish"},
{name:"Ukrainian"},
{name:"Vegan"},
{name:"Vegetarian"},
{name:"Venezuelan"},
{name:"Vietnamese"},
{name:"Wings"},
{name:"Wraps"}
]
