var fs = require('fs');
var async = require('async');
var cuisines = [
  'Afghan',
  'African',
  'Albanian',
  'Alcohol',
  'American',
  'Argentinian',
  'Asian',
  'Australian',
  'Austrian',
  'Bagels',
  'Bakery',
  'BBQ',
  'Belgian',
  'Brazilian',
  'Breakfast',
  'British',
  'Burmese',
  'Cajun',
  'Californian',
  'Calzones',
  'Cambodian',
  'Cantonese',
  'Caribbean',
  'Cheesesteaks',
  'Chicken',
  'Chili',
  'Chinese',
  'Classic',
  'Coffee and Tea',
  'Colombian',
  'Costa Rican',
  'Crepes',
  'Cuban',
  'Deli',
  'Dessert',
  'Dim Sum',
  'Diner',
  'Dinner',
  'Dominican',
  'Eclectic',
  'Ecuadorian',
  'Egyptian',
  'El Salvadoran',
  'Empanadas',
  'English',
  'Ethiopian',
  'Fast Food',
  'Filipino',
  'Fine Dining',
  'French',
  'Fresh Fruits',
  'Frozen Yogurt',
  'German',
  'Gluten-Free',
  'Greek',
  'Grill',
  'Grocery Items',
  'Guatemalan',
  'Gyro',
  'Haitian',
  'Halal',
  'Hamburgers',
  'Hawaiian',
  'Healthy',
  'Hoagies',
  'Hot Dogs',
  'Ice Cream',
  'Indian',
  'Indonesian',
  'Irish',
  'Italian',
  'Jamaican',
  'Japanese',
  'Kids Menu',
  'Korean',
  'Kosher',
  'Kosher-Style',
  'Late Night',
  'Latin American',
  'Lebanese',
  'Low Carb',
  'Low Fat',
  'Lunch',
  'Lunch Specials',
  'Malaysian',
  'Mandarin',
  'Mediterranean',
  'Mexican',
  'Middle Eastern',
  'Mongolian',
  'Moroccan',
  'Nepalese',
  'New American',
  'Noodles',
  'Organic',
  'Pakistani',
  'Pasta',
  'Persian',
  'Peruvian',
  'Pitas',
  'Pizza',
  'Polish',
  'Portuguese',
  'Potato',
  'Pub Food',
  'Puerto Rican',
  'Ribs',
  'Russian',
  'Salads',
  'Sandwiches',
  'Scandinavian',
  'Seafood',
  'Senegalese',
  'Shakes',
  'Smoothies and Juices',
  'Soul Food',
  'Soup',
  'South African',
  'South American',
  'Southern',
  'Southwestern',
  'Spanish',
  'Steak',
  'Subs',
  'Sushi',
  'Szechwan',
  'Taiwanese',
  'Tapas',
  'Tex-Mex',
  'Thai',
  'Tibetan',
  'Turkish',
  'Ukrainian',
  'Vegan',
  'Vegetarian',
  'Venezuelan',
  'Vietnamese',
  'Wings',
  'Wraps']

async.eachSeries(cuisines, function iterator(cuisine, callback) {
	console.log('processing cuisine: ', cuisine);
 fs.appendFile('./cuisines2.js', JSON.stringify({text: cuisine}) + ',\n', function(err) {
        if (err) console.log(err)
        callback()   
   })

}, function done(err){
	if (err) console.log(err)
	else console.log('done!')
})