module.exports.cuisines = [{"text":"Afghan"},
{"text":"African"},
{"text":"Albanian"},
{"text":"Alcohol"},
{"text":"American"},
{"text":"Argentinian"},
{"text":"Asian"},
{"text":"Australian"},
{"text":"Austrian"},
{"text":"Bagels"},
{"text":"Bakery"},
{"text":"BBQ"},
{"text":"Belgian"},
{"text":"Brazilian"},
{"text":"Breakfast"},
{"text":"British"},
{"text":"Burmese"},
{"text":"Cajun"},
{"text":"Californian"},
{"text":"Calzones"},
{"text":"Cambodian"},
{"text":"Cantonese"},
{"text":"Caribbean"},
{"text":"Cheesesteaks"},
{"text":"Chicken"},
{"text":"Chili"},
{"text":"Chinese"},
{"text":"Classic"},
{"text":"Coffee and Tea"},
{"text":"Colombian"},
{"text":"Costa Rican"},
{"text":"Crepes"},
{"text":"Cuban"},
{"text":"Deli"},
{"text":"Dessert"},
{"text":"Dim Sum"},
{"text":"Diner"},
{"text":"Dinner"},
{"text":"Dominican"},
{"text":"Eclectic"},
{"text":"Ecuadorian"},
{"text":"Egyptian"},
{"text":"El Salvadoran"},
{"text":"Empanadas"},
{"text":"English"},
{"text":"Ethiopian"},
{"text":"Fast Food"},
{"text":"Filipino"},
{"text":"Fine Dining"},
{"text":"French"},
{"text":"Fresh Fruits"},
{"text":"Frozen Yogurt"},
{"text":"German"},
{"text":"Gluten-Free"},
{"text":"Greek"},
{"text":"Grill"},
{"text":"Grocery Items"},
{"text":"Guatemalan"},
{"text":"Gyro"},
{"text":"Haitian"},
{"text":"Halal"},
{"text":"Hamburgers"},
{"text":"Hawaiian"},
{"text":"Healthy"},
{"text":"Hoagies"},
{"text":"Hot Dogs"},
{"text":"Ice Cream"},
{"text":"Indian"},
{"text":"Indonesian"},
{"text":"Irish"},
{"text":"Italian"},
{"text":"Jamaican"},
{"text":"Japanese"},
{"text":"Kids Menu"},
{"text":"Korean"},
{"text":"Kosher"},
{"text":"Kosher-Style"},
{"text":"Late Night"},
{"text":"Latin American"},
{"text":"Lebanese"},
{"text":"Low Carb"},
{"text":"Low Fat"},
{"text":"Lunch"},
{"text":"Lunch Specials"},
{"text":"Malaysian"},
{"text":"Mandarin"},
{"text":"Mediterranean"},
{"text":"Mexican"},
{"text":"Middle Eastern"},
{"text":"Mongolian"},
{"text":"Moroccan"},
{"text":"Nepalese"},
{"text":"New American"},
{"text":"Noodles"},
{"text":"Organic"},
{"text":"Pakistani"},
{"text":"Pasta"},
{"text":"Persian"},
{"text":"Peruvian"},
{"text":"Pitas"},
{"text":"Pizza"},
{"text":"Polish"},
{"text":"Portuguese"},
{"text":"Potato"},
{"text":"Pub Food"},
{"text":"Puerto Rican"},
{"text":"Ribs"},
{"text":"Russian"},
{"text":"Salads"},
{"text":"Sandwiches"},
{"text":"Scandinavian"},
{"text":"Seafood"},
{"text":"Senegalese"},
{"text":"Shakes"},
{"text":"Smoothies and Juices"},
{"text":"Soul Food"},
{"text":"Soup"},
{"text":"South African"},
{"text":"South American"},
{"text":"Southern"},
{"text":"Southwestern"},
{"text":"Spanish"},
{"text":"Steak"},
{"text":"Subs"},
{"text":"Sushi"},
{"text":"Szechwan"},
{"text":"Taiwanese"},
{"text":"Tapas"},
{"text":"Tex-Mex"},
{"text":"Thai"},
{"text":"Tibetan"},
{"text":"Turkish"},
{"text":"Ukrainian"},
{"text":"Vegan"},
{"text":"Vegetarian"},
{"text":"Venezuelan"},
{"text":"Vietnamese"},
{"text":"Wings"},
{"text":"Wraps"}
]
