{ ASIN: [ 'B004E06HLI' ],
  ParentASIN: [ 'B0068EB8DK' ],
  DetailPageURL: [ 'http://www.amazon.com/Doublju-Mens-Shirt-Contrast-CHARCOAL/dp/B004E06HLI%3Fpsc%3D1%26SubscriptionId%3DAKIAILD2WZTCJPBMK66A%26tag%3Dbubboorev-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB004E06HLI' ],
  ItemLinks: [ { ItemLink: [Object] } ],
  SmallImage: [ { URL: [Object], Height: [Object], Width: [Object] } ],
  MediumImage: [ { URL: [Object], Height: [Object], Width: [Object] } ],
  LargeImage: [ { URL: [Object], Height: [Object], Width: [Object] } ],
  ImageSets: [ { ImageSet: [Object] } ],
  ItemAttributes:
   [ { Binding: [Object],
       Brand: [Object],
       ClothingSize: [Object],
       Color: [Object],
       Department: [Object],
       EAN: [Object],
       EANList: [Object],
       Feature: [Object],
       IsAdultProduct: [Object],
       ListPrice: [Object],
       Model: [Object],
       NumberOfItems: [Object],
       PackageDimensions: [Object],
       ProductGroup: [Object],
       ProductTypeName: [Object],
       Size: [Object],
       Title: [Object] } ],
  OfferSummary:
   [ { LowestNewPrice: [Object],
       TotalNew: [Object],
       TotalUsed: [Object],
       TotalCollectible: [Object],
       TotalRefurbished: [Object] } ],
  Offers:
   [ { TotalOffers: [Object],
       TotalOfferPages: [Object],
       MoreOffersUrl: [Object],
       Offer: [Object] } ],
  reviews: { rating: 3.2, reviewCount: 1 } }