apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx-pay
  name: nginx-pay
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx-pay
  template:
    metadata:
      labels:
        run: nginx-pay
    spec:
      containers:
      - name: nginx-pay
        image: ymqytw/nginxhttps:1.5
        command: ["/home/auto-reload-nginx.sh"]
        ports:
        - containerPort: 443
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: ssl-certs
      - name: configmap-volume
        configMap:
          name: nginxconfigmap
