apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: slack
  namespace: canary
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - dev-slack.kipthis.com
    secretName: dev-slack-tls
  backend:
    serviceName: slack
    servicePort: 80