apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: slack
  namespace: canary
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: slack
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: canary
        - name: CONFIG_ENV
          value: canary
        image: gcr.io/kip-styles/slack:CANARYIMAGE
        imagePullPolicy: Always
        name: slack
        ports:
        - containerPort: 8000
          protocol: TCP
        readinessProbe:
          exec:
            command:
              - cat
              - /tmp/healthy
          initialDelaySeconds: 30
          timeoutSeconds: 3
        livenessProbe:
          exec:
            command:
              - cat
              - /tmp/healthy
          initialDelaySeconds: 30
          timeoutSeconds: 2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: slack
  name: slack
  namespace: canary
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: slack
  type: NodePort
