apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    run: payments
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: idk
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: ssl
  selector:
    run: payments
  type: LoadBalancer