env: production
isProduction: true
mongodb:
  url: mongodb://localhost/foundry
  backuphost: jolteon.internal.kipapp.co
  options:
    replset:
      rs_name: rs0
      socketOptions:
        keepAlive: 1
elasticsearch:
  url: http://elasticsearch-cerulean.internal.kipapp.co:9200
elasticsearchElk:
  url: http://elasticsearch-cerulean.internal.kipapp.co:9200
redis:
  port: 6379
  url: redis-thunder.internal.kipapp.co
geoipURL: http://localhost:8080/json/
neighborhoodServer:
  url: http://localhost:9998
app:
  publicAPI: https://kipapp.co/styles/api
picstitch: http://picstitch:5000
nlp: http://parser:8083
nlp_rnn: http://rnn:8085
doc2vec: http://localhost:8084
slack:
  client_id: "2804113073.84166691729"
  client_secret: 39126ac7842f6e3a010f94b9a79282f6
  verification_token: b2hLV2HnBtWBmU5NFgDBG8dL
  redirect_uri: https://canary.kipapp.co/newslack
