env: default
isProduction: false

app:
  port: 2997
  publicAPI: http://pikachu.kipapp.co/api
auth:
  jwtSecret: SlytherinOrGTFO
doc2vec: http://kadabra.kipapp.co:8084
elasticsearch:
  url: http://pikachu.kipapp.co:9200
elasticsearchElk:
  url: http://pikachu.kipapp.co:9200
facebookAuth:
  clientID: 1401271990193674
  clientSecret: 8d7c6cb160c60bd656d8a944d8f1f2bd
  callbackURL: https://kipapp.co/auth/facebook/callback,
geoipURL: http://www.freegeoip.net/json/
kipPayURL: https://pay.kipthis.com
logging:
  console:
    level: verbose
    json: false
    stringify: false
    colorize: true
    prettyPrint: true
  mongo:
    enabled: false
meetupAuth:
  consumerKey: vgmujlff2vflhtutplkaf15h
  consumerSecret: hub4tmkp966ir5q4jaaa41qc4l
  callbackURL: https://kipapp.co/auth/meetup/callback
mongodb:
  url: mongodb://localhost:27017/foundry
  backuphost: localhost
  options:
    server:
      poolSize: 5
      socketOptions:
        keepAlive: 1
mongodb2:
  url: mongodb://localhost:27017/googleCloud
  backuphost: localhost
  options:
    server:
      poolSize: 5
      socketOptions:
        keepAlive: 1
neighborhoodServer:
  url: http://pikachu.kipapp.co:9998
nlp: http://kadabra.kipapp.co:8083
picstitch: http://kadabra.kipapp.co:5000
picstitchDelivery: http://canary.kipapp.co:5000
proxy:
  luminati:
    addr: 127.0.0.1:24000
    enabled: false
    intervalMillis: 300000
    customer: kipthis
    password: change_me
    zone: gen
  mesh:
    user: alyx
    password: 9fSvNH@aB4Hs2s>qcatsoupkanyecandle
    hosts:
    - us-dc.proxymesh.com
    - us-fl.proxymesh.com
    - us-ny.proxymesh.com
    - us-il.proxymesh.com
    - us-ca.proxymesh.com
    port:
      31280
redis:
  port: 6379
  url: localhost
twitterAuth:
  consumerKey: 79AqE2SPIW219Bx35So7KfTD1
  consumerSecret: N5SmhOhWzUJwPbofLpCi0BlJ8T4M3bACpiFBaB1nHdNIOQEu6R,
  callbackURL: https://kipapp.co/auth/twitter/callback
# picstitch: http://localhost:5000
menuURL: http://localhost:8001
