env: development_mitsu
# mongodb:
#   url: localhost/foundry
elasticsearch:
  url: http://localhost:9200
app:
  publicAPI: http://localhost:2997/api
picstitch: http://dev-picstitch.kipthis.com
nlp: http://dev-parser.kipthis.com
nlp_rnn: http://dev-rnn.kipthis.com
slack:
  client_id: "17713782326.83486971505"
   # "17713782326.83486971505"
  client_secret: 74d42c3d72d9e86476734d859569a9b1
  verification_token: rF1BCPsHSBpLyw80aQ7FCGhN
  redirect_uri: https://50975b80.ngrok.io/newslack
kipPayURL: https://e6a3d0d7.ngrok.io