env: development_chris
mongodb:
  # url: localhost/foundry
  url: mongodb://localhost:27017/foundry
elasticsearch:
  url: http://localhost:9200
app:
  publicAPI: http://localhost:2997/api
picstitch: http://dev-picstitch.kipthis.com
nlp: http://dev-parser.kipthis.com
nlp_rnn: http://dev-rnn.kipthis.com
slack:
  client_id: "105555369782.117559561207"
  client_secret: 0ccce527e8ab02cfdbe3ef63a4e16bac
  verification_token: SeSOXUklO1kRQLu5sNHXilMn
  redirect_uri: https://1d200abb.ngrok.io/newslack
kipPayURL: https://14b5c738.ngrok.io
