env: development_foo
mongodb:
  url: localhost/foundry
elasticsearch:
  url: http://localhost:9200
app:
  publicAPI: http://localhost:2997/api
picstitch: http://localhost:5000
# nlp: http://localhost:8083
# doc2vec: http://localhost:8084

# 
# sample YAML init file for kip node.js scripts
#
#


globals:
        port:                   5050
        debug:                  True
        service_module:         kip_services
        log_transports:
                  - type:         winston.transports.File
                    filename:     kip.log
                    level:        debug
                    json:         false
                  
                  - type:         winston.transports.Console
                    level:        info
                    json:         false


service_objects:
        MongoDBClient:          
                init_params:
                        - username:     person
                          password:     mypass
                          host:         localhost
                          port:         27050


        DSXClient:
                init_params:
                          host:         localhost
                          port:         5000



#-----  experimental section, under development --
segments:
        snapclient:
                port:   5050
#-------------------------------------------------

