env: development_nlp
mongodb:
  url: mongodb://localhost:27017/foundry
picstitch: http://localhost:5000
nlp: http://localhost:8083
nlp_rnn: http://localhost:8085
slack:
  client_id: "40262605191.99843739429"
  client_secret: 00a0a312ef83e675243ca4102080aae1
  verification_token: twZRwtgqPxHdOMNVru9MqD6p
  redirect_uri: https://besiktasslack.localtunnel.me/newslack
kipPayURL: https://besiktaskippay.localtunnel.me