env: development_chris
mongodb:
  # url: localhost/foundry
  url: mongodb://localhost:27017/foundry
elasticsearch:
  url: http://localhost:9200
app:
  publicAPI: http://localhost:2997/api
picstitch: http://dev-picstitch.kipthis.com
nlp: http://dev-parser.kipthis.com
nlp_rnn: http://dev-rnn.kipthis.com
slack:
  client_id: "2804113073.132706161943"
  client_secret: 36c0e75b2262d4f4144cec2bae635379
  verification_token: uVonDrfiMGZ0es2OQVqyF3Jf
  redirect_uri: https://a2545e67.ngrok.io/newslack
kipPayURL: https://14b5c738.ngrok.io
