env: development-app
mongodb:
  url: mongodb://10.142.0.18/foundry
picstitch: http://dev-picstitch.kipthis.com
nlp: http://dev-parser.kipthis.com
slack:
  client_id: "2804113073.79907580837"
  client_secret: 3cebcf712a438110eac49043d85fcc7c
  verification_token: P30EDlNgjsl9i15ZQBOElJls
  redirect_uri: https://development.kipthis.com/newslack
  internal_host: https://development.kipthis.com
picstitchDelivery: http://dev-delivery-picstitch.kipthis.com
logging:
  console:
    level: silly
    json: false
    stringify: false
    colorize: true
    prettyPrint: true
  mongo:
    enabled: true
  debugFileLine:
    enabled: true
menuURL: http://development.kipthis.com/menus
kipPayURL: https://dev-pay.kipthis.com
