env: development_alyx
mongodb:
  url: mongodb://localhost:27017/foundry
  backuphost: localhost
  options:
    server:
      poolSize: 5
      socketOptions:
        keepAlive: 1
elasticsearch:
  url: http://localhost:9200
app:
  publicAPI: http://localhost:2997/api
picstitch: http://localhost:5000
# nlp: http://localhost:8083
# doc2vec: http://localhost:8084
nlp: http://dev-parser.kipthis.com
nlp_rnn: http://dev-rnn.kipthis.com
slack:
  client_id: "2804113073.157642363365"
   # "17713782326.83486971505"
  client_secret: f3fcd31fd4796952efa04b27f40674ac
  verification_token: K0R3t3LUQSxCwGZAcJBiZK5V
  redirect_uri: https://274e7bfa.ngrok.io/newslack
kipPayURL: https://7ad44111.ngrok.io
picstitchDelivery: http://localhost:5000
