env: development_mitsu
mongodb:
  url: localhost/foundry
elasticsearch:
  url: http://localhost:9200
app:
  publicAPI: http://localhost:2997/api
picstitch: http://localhost:5000
# nlp: http://localhost:8083
# doc2vec: http://localhost:8084
nlp: http://104.196.102.37:8083
nlp_rnn: http://104.196.1.204:8085

