env: development_hannah
mongodb:
  url: mongodb://localhost:27017/foundry
  backuphost: localhost
  options:
    server:
      poolSize: 5
      socketOptions:
        keepAlive: 1
elasticsearch:
  url: http://localhost:9200
slack:
  client_id: "110519934743.109767556243"
  client_secret: 4b3e730b1162664f10f4f23865e0964c
  verification_token: PyeQ1gjE81cbAWFshg24to0U
  redirect_uri: https://9a15a4d8.ngrok.io/newslack
kipPayURL: https://74e09ba2.ngrok.io
