env: development_nlp
mongodb:
  url: mongodb://localhost:27017/foundry
picstitch: http://dev-picstitch.kipthis.com
nlp: http://dev-parser.kipthis.com
nlp_rnn: http://dev-rnn.kipthis.com
slack:
  client_id: "40262605191.99843739429"
  client_secret: 00a0a312ef83e675243ca4102080aae1
  verification_token: twZRwtgqPxHdOMNVru9MqD6p
  redirect_uri: https://41a4892a.ngrok.io/newslack
kipPayURL: https://a3b3598a.ngrok.io
menuURL: https://f9d513a7.ngrok.io
picstitchDelivery: http://delivery-picstitch.kipthis.com