env: production
isProduction: true
elasticsearch:
  url: http://elasticsearch-cerulean.internal.kipapp.co:9200
kipPayURL: https://pay.kipthis.com
logging:
  console:
    level: info
    json: true
    stringify: true
    colorize: false
    prettyPrint: false
  mongo:
    enabled: true
mongodb:
  url: mongodb://10.142.0.13,10.142.0.14/foundry
  backuphost: "10.142.0.13"
  options:
    replset:
      rs_name: rs0
      socketOptions:
        keepAlive: 1
nlp: http://parser.kipthis.com
picstitch: http://picstitch.kipthis.com
proxy:
  luminati:
    addr: http://luminati-proxy.default.svc.cluster.local:22225
    enabled: true
    password: e49d4ega1696
  mesh:
    password: 9fSvNH@aB4Hs2s>qcatsoupkanyecandle
redis:
  port: 6379
  url: redis-thunder.internal.kipapp.co
slack:
  client_id: "2804113073.14708197459"
  client_secret: d4c324bf9caa887a66870abacb3d7cb5
  verification_token: P30EDlNgjsl9i15ZQBOElJls
  redirect_uri: https://slack.kipthis.com/newslack
menuURL: http://cafe.kipthis.com/menus
picstitchDelivery: http://delivery-picstitch.kipthis.com
