env: production
isProduction: true

app:
  publicAPI: https://kipapp.co/styles/api
doc2vec: http://localhost:8084
elasticsearch:
  url: http://elasticsearch-cerulean.internal.kipapp.co:9200
elasticsearchElk:
  url: http://elasticsearch-cerulean.internal.kipapp.co:9200
geoipURL: http://localhost:8080/json/
kipPayURL: https://pay.kipthis.com
logging:
  console:
    level: info
    colorize: true
    prettyPrint: true
  mongo:
    enabled: true
mongodb:
  url: mongodb://mongodb-1-server-1,mongodb-1-server-2/foundry
  backuphost: mongodb-1-server-1
  options:
    replset:
      rs_name: rs0
      socketOptions:
        keepAlive: 1
neighborhoodServer:
  url: http://localhost:9998
nlp: http://parser:8083
nlp_rnn: http://rnn:8085
picstitch: http://picstitch:5000
proxy:
  luminati:
    enabled: true
    password: e49d4ega1696
  mesh:
    password: 9fSvNH@aB4Hs2s>qcatsoupkanyecandle
redis:
  port: 6379
  url: redis-thunder.internal.kipapp.co
slack:
  client_id: "2804113073.14708197459"
  client_secret: d4c324bf9caa887a66870abacb3d7cb5
  verification_token: P30EDlNgjsl9i15ZQBOElJls
  redirect_uri: https://slack.kipapp.co/newslack
