env: test
picstitch: http://dev-picstitch.kipthis.com
nlp: http://dev-parser.kipthis.com
nlp_rnn: http://dev-rnn.kipthis.com
doc2vec: http://localhost:8084
slack:
  client_id: "52946721872.53047577702"
  client_secret: 7989b267194bfa98782340007c08d088
  verification_token: qHatSrSqnXj8ElOq5u5JGtMw
logging:
  console:
    level: warn
menuURL: 'http://localhost:8001/menus'
