// Session
export const RECEIVE_SESSION = 'RECEIVE_SESSION';
export const REQUEST_SESSION = 'REQUEST_SESSION';
export const REQUEST_UPDATE_SESSION = 'REQUEST_UPDATE_SESSION';
export const RECEIVE_UPDATE_SESSION = 'RECEIVE_UPDATE_SESSION';
export const LOGGED_IN = 'LOGGED_IN';
export const REGISTER_EMAIL = 'REGISTER_EMAIL';
export const ONBOARD_NEW_USER = 'ONBOARD_NEW_USER';
export const TOGGLE_ADDING = 'TOGGLE_ADDING';

// Cart
export const REQUEST_ADD_ITEM_TO_CART = 'REQUEST_ADD_ITEM_TO_CART';
export const RECEIVE_ADD_ITEM_TO_CART = 'RECEIVE_ADD_ITEM_TO_CART';
export const ADD_MEMBER_TO_CART = 'ADD_MEMBER_TO_CART';
export const REMOVE_MEMBER_FROM_CART = 'REMOVE_MEMBER_FROM_CART';
export const RECEIVE_CART = 'RECEIVE_CART';
export const REQUEST_CART = 'REQUEST_CART';
export const REQUEST_REMOVE_ITEM_FROM_CART = 'REQUEST_REMOVE_ITEM_FROM_CART';
export const RECEIVE_REMOVE_ITEM_FROM_CART = 'RECEIVE_REMOVE_ITEM_FROM_CART';
export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';
export const ADDING_ITEM = 'ADDING_ITEM';
export const SELECT_ITEM = 'SELECT_ITEM';

// Deals
export const REQUEST_DEALS = 'REQUEST_DEALS';
export const RECEIVE_DEALS = 'RECEIVE_DEALS';

// Item
export const REQUEST_ITEM = 'REQUEST_ITEM';
export const RECEIVE_ITEM = 'RECEIVE_ITEM';

