// react/constants/ActionTypes.js

// Session
export const RECEIVE_SESSION = 'RECEIVE_SESSION';
export const REQUEST_SESSION = 'REQUEST_SESSION';
export const REQUEST_UPDATE_SESSION = 'REQUEST_UPDATE_SESSION';
export const RECEIVE_UPDATE_SESSION = 'RECEIVE_UPDATE_SESSION';
export const LOGGED_IN = 'LOGGED_IN';
export const REGISTER_EMAIL = 'REGISTER_EMAIL';
export const ONBOARD_NEW_USER = 'ONBOARD_NEW_USER';
export const TOGGLE_ADDING = 'TOGGLE_ADDING';
export const UPDATE_USER = 'UPDATE_USER';

// Cart
export const RECEIVE_CART = 'RECEIVE_CART';
export const REQUEST_CART = 'REQUEST_CART';
export const RECEIVE_CARTS = 'RECEIVE_CARTS';
export const REQUEST_CARTS = 'REQUEST_CARTS';
export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';
export const ADDING_ITEM = 'ADDING_ITEM';
export const ADD_MEMBER_TO_CART = 'ADD_MEMBER_TO_CART';
export const RECEIVE_UPDATE_CART = 'RECEIVE_UPDATE_CART';
export const REQUEST_CLEAR_CART = 'REQUEST_CLEAR_CART';
export const RECEIVE_CLEAR_CART = 'RECEIVE_CLEAR_CART';
export const CANCEL_CLEAR_CART = 'CANCEL_CLEAR_CART';

// Cards
export const REQUEST_CARDS = 'REQUEST_CARDS';
export const RECEIVE_CARDS = 'RECEIVE_CARDS';
export const SELECT_CARD = 'SELECT_CARD';
export const REMOVE_CARD = 'REMOVE_CARD';

// Item
export const REQUEST_ITEM = 'REQUEST_ITEM';
export const RECEIVE_ITEM = 'RECEIVE_ITEM';
export const CLEAR_ITEM = 'CLEAR_ITEM';
export const REQUEST_ADD_ITEM = 'REQUEST_ADD_ITEM';
export const RECEIVE_ADD_ITEM = 'RECEIVE_ADD_ITEM';
export const REQUEST_REMOVE_ITEM = 'REQUEST_REMOVE_ITEM';
export const RECEIVE_REMOVE_ITEM = 'RECEIVE_REMOVE_ITEM';
export const CANCEL_REMOVE_ITEM = 'CANCEL_REMOVE_ITEM';
export const RECEIVE_INCREMENT_ITEM = 'RECEIVE_INCREMENT_ITEM';
export const REQUEST_INCREMENT_ITEM = 'REQUEST_INCREMENT_ITEM';
export const RECEIVE_DECREMENT_ITEM = 'RECEIVE_DECREMENT_ITEM';
export const REQUEST_DECREMENT_ITEM = 'REQUEST_DECREMENT_ITEM';
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH';
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY';
export const SEARCH_NEXT = 'SEARCH_NEXT';
export const SEARCH_PREV = 'SEARCH_PREV';
export const SET_SEARCH_INDEX = 'SET_SEARCH_INDEX';

//cart stores
export const REQUEST_STORES = 'REQUEST_STORES';
export const RECEIVE_STORES = 'RECEIVE_STORES';
export const REQUEST_SET_STORE = 'REQUEST_SET_STORE';
export const RECEIVE_SET_STORE = 'RECEIVE_SET_STORE';
