// Session
export const RECEIVE_SESSION = 'RECEIVE_SESSION';
export const REQUEST_SESSION = 'REQUEST_SESSION';
export const REQUEST_UPDATE_SESSION = 'REQUEST_UPDATE_SESSION';
export const RECEIVE_UPDATE_SESSION = 'RECEIVE_UPDATE_SESSION';

// Cart
export const REQUEST_ADD_ITEM_TO_CART = 'REQUEST_ADD_ITEM_TO_CART';
export const RECEIVE_ADD_ITEM_TO_CART = 'RECEIVE_ADD_ITEM_TO_CART';
export const ADD_MEMBER_TO_CART = 'ADD_MEMBER_TO_CART';
export const REMOVE_MEMBER_FROM_CART = 'REMOVE_MEMBER_FROM_CART';
export const RECEIVE_CART = 'RECEIVE_CART';
export const REQUEST_CART = 'REQUEST_CART';
export const REQUEST_REMOVE_ITEM_FROM_CART = 'REQUEST_REMOVE_ITEM_FROM_CART';
export const RECEIVE_REMOVE_ITEM_FROM_CART = 'RECEIVE_REMOVE_ITEM_FROM_CART';
export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';
export const SET_CART_ID = 'SET_CART_ID';
export const LOGGED_IN = 'LOGGED_IN';
export const LOG_IN = 'LOG_IN';

// Item
export const RECEIVE_ITEM_INFO = 'RECEIVE_ITEM_INFO';
export const REQUEST_ITEM_INFO = 'REQUEST_ITEM_INFO';
