module.exports = {
  "Appliances": 'Appliances',
  "Arts, Crafts, & Sewing": 'ArtsAndCrafts',
  "Automotive": 'Automotive',
  "Baby": 'Baby',
  "Beauty": 'Beauty',
  "Books": 'Books',
  "Collectibles & Fine Arts": 'Collectibles',
  "Electronics": 'Electronics',
  "Clothing, Shoes & Jewelry": 'Fashion',
  "Clothing, Shoes & Jewelry - Baby": "FashionBaby",
  "Clothing, Shoes & Jewelry - Boys": "FashionBoys",
  "Clothing, Shoes & Jewelry - Girls": "FashionGirls",
  "Clothing, Shoes & Jewelry - Men": "FashionMen",
  "Clothing, Shoes & Jewelry - Women": "FashionWomen",
  "Gift Cards": 'GiftCards',
  "Grocery & Gourmet Food": 'Grocery',
  "Handmade": 'Handmade',
  "Health & Personal Care": 'HealthPersonalCare',
  "Home & Kitchen": 'HomeGarden',
  "Industrial & Scientific": 'Industrial',
  "Kindle Store": "KindleStore",
  "Patio, Lawn & Garden": 'LawnAndGarden',
  "Luggage & Travel Gear": 'Luggage',
  "Magazine Subscriptions": 'Magazines',
  "Apps & Games": 'MobileApps',
  "Movies & TV": 'Movies',
  "Digital Music": 'MP3Downloads',
  "CDs & Vinyl": 'Music',
  "Musical Instruments": 'MusicalInstruments',
  "Office Products": 'OfficeProducts',
  "Prime Pantry": 'Pantry',
  "Computers": 'PCHardware',
  "Pet Supplies": 'PetSupplies',
  "Software": 'Software',
  "Sports & Outdoors": 'SportingGoods',
  "Tools & Home Improvement": 'Tools',
  "Toys and Games": 'Toys',
  "Amazon Instant Video": 'UnboxVideo',
  "Vehicles": 'Vehicles',
  "Video Games": 'VideoGames',
  "Wine": 'Wine',
  "Cell Phones & Accessories": 'Wireless'
}
