apiVersion: v1
kind: Service
metadata:
  labels:
    run: facebook
  name: facebook
spec:
  ports:
  - port: 4343
    protocol: TCP
    targetPort: 4343
  selector:
    run: facebook
  type: LoadBalancer
