Image: "minio/minio"
ImageTag: "latest"
ImagePullPolicy: "Always"

ServiceType: ClusterIP
ServicePort: 9000

## Set default access key and secret
AccessKey: "DNAMPOSFN7EXAKIAIOLE"
SecretKey: "ENAMPLEKEYwG/bPxRfiCYEXJalrXUtnFEMI/K7MD"

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  storageClass: generic
  accessMode: ReadWriteOnce
  size: 500Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 512Mi
    cpu: 500m