apiVersion: v1
metadata:
  name: kube-lego
  namespace: kube-lego
data:
  lego.email: "graham@interfacefoundry.com"
  # configre letencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
kind: ConfigMap